### ISSUE TITLE
[feat] Category works in Todo Modal

### ISSUE THREAD

**Issue by enigsuss** [Kernel360/FE1_E2E_sumtime#159]
## Feature Name
- 카테고리의 CRUD 작업을 Todo Modal 내에서 가능하도록 구현합니다.

## Progress

- [x] Category 필드에서 1개만 선택 가능하도록 수정
- [x] Category 필드에서 선택 요소에 색상 적용
- [x] Categroy 필드 CRUD 기능 구현
